name: Run Tests on PR

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'main/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: npm install --save-dev

      - name: Run Tests
        run: npx c8 --check-coverage npx tsx --test --test-reporter tap --test-reporter-destination tests.tap --test-reporter spec --test-reporter-destination tests.spec tests/**/*.ts
    
      - name: Upload test results artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: tests-results
          path: |
            tests.tap
            tests.spec
            ./coverage

