name: Run Tests on PR

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'main/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: npm install --save-dev

      - name: Run Tests
        run: npm test
